#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqMeUp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Corona")]
	public partial class ElephantDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttheStat(theStat instance);
    partial void UpdatetheStat(theStat instance);
    partial void DeletetheStat(theStat instance);
    #endregion
		
		public ElephantDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CoronaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ElephantDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElephantDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElephantDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ElephantDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<theStat> theStats
		{
			get
			{
				return this.GetTable<theStat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.theStats")]
	public partial class theStat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _countrycode;
		
		private System.DateTime _date;
		
		private System.Nullable<int> _cases;
		
		private System.Nullable<int> _deaths;
		
		private System.Nullable<int> _recovered;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncountrycodeChanging(string value);
    partial void OncountrycodeChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OncasesChanging(System.Nullable<int> value);
    partial void OncasesChanged();
    partial void OndeathsChanging(System.Nullable<int> value);
    partial void OndeathsChanged();
    partial void OnrecoveredChanging(System.Nullable<int> value);
    partial void OnrecoveredChanged();
    #endregion
		
		public theStat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countrycode", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string countrycode
		{
			get
			{
				return this._countrycode;
			}
			set
			{
				if ((this._countrycode != value))
				{
					this.OncountrycodeChanging(value);
					this.SendPropertyChanging();
					this._countrycode = value;
					this.SendPropertyChanged("countrycode");
					this.OncountrycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="SmallDateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cases", DbType="Int")]
		public System.Nullable<int> cases
		{
			get
			{
				return this._cases;
			}
			set
			{
				if ((this._cases != value))
				{
					this.OncasesChanging(value);
					this.SendPropertyChanging();
					this._cases = value;
					this.SendPropertyChanged("cases");
					this.OncasesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deaths", DbType="Int")]
		public System.Nullable<int> deaths
		{
			get
			{
				return this._deaths;
			}
			set
			{
				if ((this._deaths != value))
				{
					this.OndeathsChanging(value);
					this.SendPropertyChanging();
					this._deaths = value;
					this.SendPropertyChanged("deaths");
					this.OndeathsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovered", DbType="Int")]
		public System.Nullable<int> recovered
		{
			get
			{
				return this._recovered;
			}
			set
			{
				if ((this._recovered != value))
				{
					this.OnrecoveredChanging(value);
					this.SendPropertyChanging();
					this._recovered = value;
					this.SendPropertyChanged("recovered");
					this.OnrecoveredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
